table Store
	lineageTag: 68ea7736-b37a-5ea0-a4c6-5c7c2d1685e6

	column 'Store ID'
		dataType: int64
		isKey
		lineageTag: d772858c-9da3-5ed6-a331-69110ad3d88d
		summarizeBy: none
		sourceColumn: Store ID

		annotation SummarizationSetBy = Automatic

	column 'Store Name'
		dataType: string
		lineageTag: db04fe37-723a-5f73-8c73-c3e59c032c36
		summarizeBy: none
		sourceColumn: Store Name

		annotation SummarizationSetBy = Automatic

	column 'Store Type'
		dataType: string
		lineageTag: 89246b7d-6a77-52b4-aec0-db23fbd320ba
		summarizeBy: none
		sourceColumn: Store Type

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e978760e-ef12-52f9-a9b2-990b9cfcec27
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: f745b5b3-9516-59ea-b787-a1cefbb14dcc
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3f891fb2-0cfe-55cf-a1a6-00368278a561
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 67637f6b-0804-5534-a3c9-f8e11edffa46
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Open Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cc4deb1f-e4db-5ee4-b9e8-1030e0646ba1
		summarizeBy: none
		sourceColumn: Open Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Latitude
		dataType: double
		lineageTag: 7ffaf948-a30a-5eb6-9cf2-87f398d6cc12
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: 189d5bb9-c0e7-5d7c-b042-a055d132b53a
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

	column 'Square Feet'
		dataType: int64
		lineageTag: 141763eb-e06f-5b38-b294-cd86fa50a4fe
		summarizeBy: none
		sourceColumn: Square Feet

		annotation SummarizationSetBy = Automatic

	partition Store = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Demo\Data\Store.csv"), [Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Store ID", Int64.Type}, {"Store Name", Text.Type}, {"Store Type", Text.Type}, {"City", Text.Type}, {"State", Text.Type}, {"Region", Text.Type}, {"Country", Text.Type}, {"Open Date", type date}, {"Latitude", Double.Type}, {"Longitude", Double.Type}, {"Square Feet", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

