/// Forecast average revenue per visit for each store for each month in 2024
table 'Average Revenue per Visit Forecast 2024'
	lineageTag: 2eefa650-d9db-4e9d-b611-37250db746bd

	/// The forecast average revenue per visit
	measure 'Avg Revenue per Visit Forecast' =
			
			AVERAGEX(
			    'Average Revenue per Visit Forecast 2024',
			    AVERAGE([Forecast Average Revenue per Visit])
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 84cef37e-9d9c-47ef-90ee-e400c09840c7

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Returns the average revenue in excess of the forecasted average revenue, as a percentage of the forecast
	measure 'Avg Revenue per Visit over Forecast with Arrow' = ```
			
			VAR varMeasure = [Avg Revenue per Visit over Forecast]
			VAR varUpArrow = UNICHAR(129129)
			VAR varDownArrow = UNICHAR(129131)
			VAR varMeasureWithUpArrow = FORMAT(varMeasure, "#,0.0%") & " " & varUpArrow
			VAR varMeasureWithDownArrow = FORMAT(varMeasure, ";(#,0.0%)") & " " & varDownArrow
			VAR varResult = 
			    SWITCH(
			        TRUE(),
			        varMeasure > 0, varMeasureWithUpArrow,
			        varMeasure < 0, varMeasureWithDownArrow,
			        varMeasure
			    )
			RETURN varResult
			```
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 818d2dc6-e32a-466e-89ce-91fdcd45dd5d

	/// Returns the average revenue in excess of the forecasted average revenue, as a percentage of the forecast
	measure 'Avg Revenue per Visit over Forecast' =
			
			DIVIDE(
			    [Avg Revenue per Visit] - [Avg Revenue per Visit Forecast],
			    [Avg Revenue per Visit Forecast],
			    BLANK()
			)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 9c02f7ff-6639-4d38-bded-8b7fd65202a1

	/// Returns "Green" when the [Avg Revenue per Visit over Forecast] measure is positive, "Red" when negative, and "Black otherwise (i.e., when 0).  This measure is used for conditionally formatting the [Avg Revenue per Visit over Forecast with Arrow] measure.
	measure 'Avg Revenue per Visit over Forecast with Arrow Conditional Formatting' = ```
			
			VAR varMeasure = [Avg Revenue per Visit over Forecast]
			VAR varResult = 
			    SWITCH(
			        TRUE(),
			        varMeasure > 0, "#1CBAA4",
			        varMeasure < 0, "#FD625E",
			        "#252423"
			    )
			RETURN varResult
			```
		lineageTag: 1bb8ed96-7a56-42dc-9810-fcb7a76c5f51

	/// The ID for the store.  The primary key for the table.
	column 'Store ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d3d3a917-32b3-4720-a6c9-1319288e3c89
		summarizeBy: none
		sourceColumn: Store ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The month for which the forecast is made
	column Month
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 569fbef2-14cc-4d50-a916-a26f9bbbef8a
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The forecast average revenue per visit for the given store in the given month
	column 'Forecast Average Revenue per Visit'
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c7321c11-0a5a-4307-bd02-ca31fa9172b5
		summarizeBy: none
		sourceColumn: Forecast Average Revenue per Visit

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition 'Average Revenue per Visit Forecast 2024' = m
		mode: import
		queryGroup: 'Fact Queries'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Demo\Data\Forecast 2024.xlsx"), null, true),
				    AvgRevPerVisitForecast2024_Table = Source{[Item="AvgRevPerVisitForecast2024",Kind="Table"]}[Data],
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(AvgRevPerVisitForecast2024_Table, {"Store ID"}, "Month", "Forecast Average Revenue per Visit"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Unpivoted Other Columns",{{"Store ID", Int64.Type}, {"Month", type date}, {"Forecast Average Revenue per Visit", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

