/// Contains data on revenue per visit at the stores.  This table is at a grain of Store-Date.
table 'Average Revenue per Visit'
	lineageTag: af828466-da2b-46ef-8643-6258a1679cbd

	/// The average revenue per visit
	measure 'Avg Revenue per Visit' =
			
			AVERAGE([Average Revenue per Visit])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 28aaeca3-4d78-4803-9180-69ea08fd5c5d

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// The average revenue per visit for the same period last year
	measure 'Avg Revenue per Visit SPLY' =
			
			CALCULATE(
			    [Avg Revenue per Visit],
			    SAMEPERIODLASTYEAR('Date'[Date])
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5dbbd99f-5869-4ac0-bcd5-4a7b93aca2f1

	/// Returns the year-over-year (YoY) growth percentage (%) of average revenue per visit, computed by comparing the [Avg Revenue per Visit] to the [Avg Revenue per Visit SPLY]
	measure 'Avg Revenue per Visit YoY with Arrow' = ```
			
			VAR varMeasure = [Avg Revenue per Visit YoY]
			VAR varUpArrow = UNICHAR(129129)
			VAR varDownArrow = UNICHAR(129131)
			VAR varMeasureWithUpArrow = FORMAT(varMeasure, "#,0.0%") & " " & varUpArrow
			VAR varMeasureWithDownArrow = FORMAT(varMeasure, ";(#,0.0%)") & " " & varDownArrow
			VAR varResult = 
			    SWITCH(
			        TRUE(),
			        varMeasure > 0, varMeasureWithUpArrow,
			        varMeasure < 0, varMeasureWithDownArrow,
			        varMeasure
			    )
			RETURN varResult
			```
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 318cdab2-72e5-475c-847d-7d9139c61937

	/// Returns the year-over-year (YoY) growth percentage (%) of average revenue per visit, computed by comparing the [Avg Revenue per Visit] to the [Avg Revenue per Visit SPLY]
	measure 'Avg Revenue per Visit YoY' =
			
			DIVIDE(
			    [Avg Revenue per Visit] - [Avg Revenue per Visit SPLY],
			    [Avg Revenue per Visit SPLY],
			    BLANK()
			)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 0ce4636d-7d97-4bfb-8480-776495aec02d

	/// Returns "Green" when the [Avg Revenue per Visit YoY] measure is positive, "Red" when negative, and "Black otherwise (i.e., when 0).  This measure is used for conditionally formatting the [Avg Revenue per Visit YoY with Arrow] measure.
	measure 'Avg Revenue per Visit YoY with Arrow Conditional Formatting' = ```
			
			VAR varMeasure = [Avg Revenue per Visit YoY]
			VAR varResult = 
			    SWITCH(
			        TRUE(),
			        varMeasure > 0, "#1CBAA4",
			        varMeasure < 0, "#FD625E",
			        "#252423"
			    )
			RETURN varResult
			```
		lineageTag: 06b54b86-049d-4b6e-bb24-fec8c0bfb475

	/// The Date of the record for the given store
	column Date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: d6d2a1d5-c66e-4c5d-9870-6ddb5db93f02
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The Store ID of the record for the given date
	column 'Store ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3f77ae01-2dca-4ea6-ba79-36df32b3fa4b
		summarizeBy: none
		sourceColumn: Store ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The average revenue per purchaser at the given store on the given date
	column 'Average Revenue per Visit'
		dataType: double
		isHidden
		formatString: #,0.00
		lineageTag: f968c2bb-1630-464d-bd97-a16219f9e60b
		summarizeBy: none
		sourceColumn: Average Revenue per Visit

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition 'Average Revenue per Visit' = m
		mode: import
		queryGroup: 'Fact Queries'
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Demo\Data\fctAverageRevenuePerVisit.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Store ID", Int64.Type}, {"Date", type date}, {"Average Revenue per Visit", type number}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

