/// Contains data on revenue stores.  This table is at a grain of Store-Date.
table 'Revenue per Store'
	lineageTag: 31899c89-c48d-47b2-ad3c-c1220958286d

	/// The total revenue
	measure 'Total Revenue' =
			
			SUM('Revenue per Store'[Revenue])
		lineageTag: b2e97799-65b7-4764-8f09-22b6b71c3682

		formatStringDefinition =
				SWITCH(
				    TRUE(),
				    SELECTEDMEASURE() > 10^10, "$0,,,.0B",
				    SELECTEDMEASURE() > 10^9, "$0,,,.00B",
				    SELECTEDMEASURE() > 10^8, "$0,,.M",
				    SELECTEDMEASURE() > 10^7, "$0,,.0M",
				    SELECTEDMEASURE() > 10^6, "$0,,.00M",
				    SELECTEDMEASURE() > 10^5, "$0,.k",
				    SELECTEDMEASURE() > 10^4, "$0,.0k",
				    "$0,0"
				)

	/// The total revenue for the same period last year
	measure 'Total Revenue SPLY' =
			
			CALCULATE(
			    [Total Revenue],
			    SAMEPERIODLASTYEAR('Date'[Date])
			)
		lineageTag: 216c55c9-9cd4-4f83-bfef-c591a7b064a9

		formatStringDefinition =
				SWITCH(
				    TRUE(),
				    SELECTEDMEASURE() > 10^10, "$0,,,.0B",
				    SELECTEDMEASURE() > 10^9, "$0,,,.00B",
				    SELECTEDMEASURE() > 10^8, "$0,,.M",
				    SELECTEDMEASURE() > 10^7, "$0,,.0M",
				    SELECTEDMEASURE() > 10^6, "$0,,.00M",
				    SELECTEDMEASURE() > 10^5, "$0,.k",
				    SELECTEDMEASURE() > 10^4, "$0,.0k",
				    "$0,0"
				)

	/// Returns the year-over-year (YoY) growth percentage (%) of total revenue, computed by comparing the [Total Revenue] to the [Total Revenue SPLY]
	measure 'Total Revenue YoY with Arrow' = ```
			
			VAR varMeasure = [Total Revenue YoY]
			VAR varUpArrow = UNICHAR(129129)
			VAR varDownArrow = UNICHAR(129131)
			VAR varMeasureWithUpArrow = FORMAT(varMeasure, "#,0.0%") & " " & varUpArrow
			VAR varMeasureWithDownArrow = FORMAT(varMeasure, ";(#,0.0%)") & " " & varDownArrow
			VAR varResult = 
			    SWITCH(
			        TRUE(),
			        varMeasure > 0, varMeasureWithUpArrow,
			        varMeasure < 0, varMeasureWithDownArrow,
			        varMeasure
			    )
			RETURN varResult
			```
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 5a7e88e1-d521-4c82-a8c8-4c22bc9dd686

	/// Returns the year-over-year (YoY) growth percentage (%) of total revenue, computed by comparing the [Total Revenue] to the [Total Revenue SPLY]
	measure 'Total Revenue YoY' =
			
			DIVIDE(
			    [Total Revenue] - [Total Revenue SPLY],
			    [Total Revenue SPLY],
			    BLANK()
			)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 571ca8fb-1a75-46c2-b16a-71eb98c74f3a

	/// Returns "Green" when the [Total Revenue YoY] measure is positive, "Red" when negative, and "Black otherwise (i.e., when 0).  This measure is used for conditionally formatting the [Total Revenue YoY with Arrow] measure.
	measure 'Total Revenue YoY with Arrow Conditional Formatting' = ```
			
			VAR varMeasure = [Total Foot Traffic YoY]
			VAR varResult = 
			    SWITCH(
			        TRUE(),
			        varMeasure > 0, "#1CBAA4",
			        varMeasure < 0, "#FD625E",
			        "#252423"
			    )
			RETURN varResult
			```
		lineageTag: 9f1ac6e3-ba60-40de-814c-2c41d65299e9

	/// The Store ID of the record for the given date
	column 'Store ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 193d623b-7844-42c8-ba94-0c7791ccf593
		summarizeBy: none
		sourceColumn: Store ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The Date of the record for the given store
	column Date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: b9e0fd2c-068f-4c59-bab9-9d9d27866538
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The revenue at the given store on the given date
	column Revenue
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3368f5a7-db7f-4cd8-85c3-6ed327604fa6
		summarizeBy: none
		sourceColumn: Revenue

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition 'Revenue per Store' = m
		mode: import
		queryGroup: 'Fact Queries'
		source =
				let
				    FootTraffic = #"Foot Traffic",
				    #"Added Foot Traffic ID" = Table.AddColumn(FootTraffic, "Foot Traffic ID", each Number.ToText([Store ID]) & "_" & Date.ToText([Date]), type text),
				    AvgRevPerVisit = #"Average Revenue per Visit",
				    #"Added ARV ID" = Table.AddColumn(AvgRevPerVisit, "ARV ID", each Number.ToText([Store ID]) & "_" & Date.ToText([Date]), type text),
				    #"Merged Foot Traffic and ARV Queries" = Table.NestedJoin(#"Added ARV ID", {"ARV ID"}, #"Added Foot Traffic ID", {"Foot Traffic ID"}, "Foot Traffic", JoinKind.LeftOuter),
				    #"Extracted Foot Traffic" = Table.ExpandTableColumn(#"Merged Foot Traffic and ARV Queries", "Foot Traffic", {"Foot Traffic"}, {"Foot Traffic"}),
				    #"Added Revenue" = Table.AddColumn(#"Extracted Foot Traffic", "Revenue", each [Average Revenue per Visit] * [Foot Traffic], Currency.Type),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Revenue",{"Average Revenue per Visit", "ARV ID", "Foot Traffic"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

