/// Forecast revenue for each store for each month in 2024
table 'Revenue per Store Forecast 2024'
	lineageTag: c56be003-2577-4e4f-8cdb-1ae46e1b9bb2

	/// The total forecast revenue
	measure 'Total Forecast Revenue' =
			
			SUM('Revenue per Store Forecast 2024'[Revenue Forecast])
		lineageTag: ec8ba7af-0fe6-4b17-a6e4-20d62a2b1b8c

		formatStringDefinition =
				SWITCH(
				    TRUE(),
				    SELECTEDMEASURE() > 10^10, "$0,,,.0B",
				    SELECTEDMEASURE() > 10^9, "$0,,,.00B",
				    SELECTEDMEASURE() > 10^8, "$0,,.M",
				    SELECTEDMEASURE() > 10^7, "$0,,.0M",
				    SELECTEDMEASURE() > 10^6, "$0,,.00M",
				    SELECTEDMEASURE() > 10^5, "$0,.k",
				    SELECTEDMEASURE() > 10^4, "$0,.0k",
				    "$0,0"
				)

	/// Returns the total revenue in excess of the forecasted total revenue, as a percentage of the forecast
	measure 'Total Revenue over Forecast with Arrow' = ```
			
			VAR varMeasure = [Total Revenue over Forecast]
			VAR varUpArrow = UNICHAR(129129)
			VAR varDownArrow = UNICHAR(129131)
			VAR varMeasureWithUpArrow = FORMAT(varMeasure, "#,0.0%") & " " & varUpArrow
			VAR varMeasureWithDownArrow = FORMAT(varMeasure, ";(#,0.0%)") & " " & varDownArrow
			VAR varResult = 
			    SWITCH(
			        TRUE(),
			        varMeasure > 0, varMeasureWithUpArrow,
			        varMeasure < 0, varMeasureWithDownArrow,
			        varMeasure
			    )
			RETURN varResult
			```
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 6ae79ccc-158d-4993-abc0-78ab3889a0ec

	/// Returns the total revenue in excess of the forecasted total revenue, as a percentage of the forecast
	measure 'Total Revenue over Forecast' =
			
			DIVIDE(
			    [Total Revenue] - [Total Forecast Revenue],
			    [Total Forecast Revenue],
			    BLANK()
			)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 8c00ba43-e6ce-45e0-91cf-19effb4924da

	/// Returns "Green" when the [Total Revenue over Forecast] measure is positive, "Red" when negative, and "Black otherwise (i.e., when 0).  This measure is used for conditionally formatting the [Total Revenue over Forecast with Arrow] measure.
	measure 'Total Revenue over Forecast with Arrow Conditional Formatting' = ```
			
			VAR varMeasure = [Total Revenue over Forecast]
			VAR varResult = 
			    SWITCH(
			        TRUE(),
			        varMeasure > 0, "#1CBAA4",
			        varMeasure < 0, "#FD625E",
			        "#252423"
			    )
			RETURN varResult
			```
		lineageTag: bac3e1a1-3355-4945-ab0f-28600f1c57db

	/// The ID for the store.  The primary key for the table.
	column 'Store ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ef36bda7-71c5-4c46-935a-b7ffc1ac6c76
		summarizeBy: none
		sourceColumn: Store ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The month for which the forecast is made
	column Month
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: ca1ece2c-4005-472e-9283-89089cd3bff4
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The forecast revenue for the given store in the given month
	column 'Revenue Forecast'
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bfe2bc57-6811-4e60-b1fe-cb0b9e3d8a14
		summarizeBy: none
		sourceColumn: Revenue Forecast

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition 'Revenue per Store Forecast 2024' = m
		mode: import
		queryGroup: 'Fact Queries'
		source =
				let
				    FootTrafficForecast = #"Foot Traffic Forecast 2024",
				    #"Added Foot Traffic ID" = Table.AddColumn(FootTrafficForecast, "Foot Traffic ID", each Number.ToText([Store ID]) & "_" & Date.ToText([Month]), type text),
				    RevPerVisitForecast = #"Average Revenue per Visit Forecast 2024",
				    #"Added RPV ID" = Table.AddColumn(RevPerVisitForecast, "RPV ID", each Number.ToText([Store ID]) & "_" & Date.ToText([Month]), type text),
				    #"Merged Foot Traffic and RPV Queries" = Table.NestedJoin(#"Added RPV ID", {"RPV ID"}, #"Added Foot Traffic ID", {"Foot Traffic ID"}, "Foot Traffic Forecast 2024", JoinKind.LeftOuter),
				    #"Extracted Foot Traffic Forecast" = Table.ExpandTableColumn(#"Merged Foot Traffic and RPV Queries", "Foot Traffic Forecast 2024", {"Foot Traffic Forecast"}, {"Foot Traffic Forecast"}),
				    #"Added Revenue Forecast" = Table.AddColumn(#"Extracted Foot Traffic Forecast", "Revenue Forecast", each [Forecast Average Revenue per Visit] * [Foot Traffic Forecast], Currency.Type),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Revenue Forecast",{"Forecast Average Revenue per Visit", "RPV ID", "Foot Traffic Forecast"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

