/// Customer dimension; one row per customer. Region drives row-level security — viewers in the East Region role see only East customers.
table Customer
	lineageTag: b7302858-80c1-5e4f-933a-b5b5652338b2

	/// Surrogate key. Hidden because consumers should filter by Customer Name or Region, not by the internal ID.
	column 'Customer ID'
		dataType: int64
		isHidden
		isKey
		isAvailableInMdx: false
		lineageTag: f76c4d6d-a090-50e9-8533-7f3060c1ded4
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	/// Customer's display name.
	column 'Customer Name'
		dataType: string
		lineageTag: 95504a98-c763-532e-8e04-4af1d0566e3a
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	/// Geographic region — East / West / North / South. Drives both static RLS (East Region role) and dynamic RLS (Regional Manager role via the disconnected User Region table).
	column Region
		dataType: string
		lineageTag: 085f8d08-aa3c-5e91-b876-a01c0f88568b
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Demo\Data\customer.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Customer ID", Int64.Type}, {"Customer Name", Text.Type}, {"Region", Text.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

