// Generated by scripts/vendor-inspector-rules.mjs. Do not edit by hand.
// Source: Rules/Base-rules.json from https://github.com/NatVanG/fab-inspector at commit cdaaeec3cca8e97b0fd493e080dfa264f9cd44f8
// (MIT License, see NOTICE). Source sha256: 22868be9acd696c96e62f214dbe0efc72fd1bfffda1736b3b9a4d7fba21f883c

export interface InspectorRuleMeta {
  id: string;
  name: string;
  description: string;
  /** The source's part, "Report" or "Pages", or absent; nothing in pbiplint reads it. */
  part?: string;
  /** Shipped off in the source; pbiplint ships every rule on. */
  disabled: boolean;
}

export const INSPECTOR_RULES: readonly InspectorRuleMeta[] = [
  {
    id: "REMOVE_UNUSED_CUSTOM_VISUALS",
    name: "Remove custom visuals which are not used in the report",
    description:
      "Returns an array of custom visual names to be removed if any. To disable this rule, mark it as disabled in the base rules file.",
    part: "Report",
    disabled: false,
  },
  {
    id: "REDUCE_VISUALS_ON_PAGE",
    name: "Reduce the number of visible visuals on the page",
    description:
      "Reports a test fail if the rule's maximum number of visible visuals on the page is exceeded. By default the base rules file specifies 20 as the maximum, set the paramMaxVisualsPerPage parameter to change this. To disable this rule, mark it as disabled in the base rules file.",
    part: "Pages",
    disabled: false,
  },
  {
    id: "REDUCE_OBJECTS_WITHIN_VISUALS",
    name: "Reduce the number of objects within visuals",
    description:
      "Reports a test fail if the rule's maximum number of objects within visuals on a page is exceeded. An object is a data field that is assigned to a visual. By default, the base rules file specifies 6 as the maximum objects within a visual. To disable this rule, mark it as disabled in the base rules file.",
    part: "Pages",
    disabled: false,
  },
  {
    id: "REDUCE_TOPN_FILTERS",
    name: "Reduce usage of TopN filtering visuals by page",
    description:
      "Reports a test fail if the rule's maximum number of visuals using TopN filtering on a the page is exceeded. By default the base rules file specifies 4 as the maximum objects within a visual, set the paramMaxTopNFilteringPerPage to change this. To disable this rule, mark it as disabled in the base rules file.",
    part: "Pages",
    disabled: false,
  },
  {
    id: "REDUCE_ADVANCED_FILTERS",
    name: "Reduce usage of Advanced filtering visuals by page",
    description:
      "Reports a test fail if the rule's maximum number of visuals using Advanced filtering on a the page is exceeded. By default, the base rules file specifies 4 as the maximum objects within a visual, set the paramMaxAdvancedFilteringVisualsPerPage parameter value to change this. To disable this rule, mark it as disabled in the base rules file",
    part: "Pages",
    disabled: false,
  },
  {
    id: "REDUCE_PAGES",
    name: "Reduce number of pages per report",
    description:
      "Reports a test fail if the rule's maximum number of pages per report is exceeded. By default, the base rules file specifies 10 as the maximum number of pages. Set the paramMaxNumberOfPagesPerReport parameter to change this. To disable this rule, mark it as disabled in the base rules file.",
    disabled: false,
  },
  {
    id: "AVOID_SHOW_ITEMS_WITH_NO_DATA",
    name: "Avoid setting ‘Show items with no data’ on columns",
    description:
      "Returns an array of visual names which have the option ‘Show items with no data’ enabled on one or more columns. To disable this rule, mark it as disabled in the base rules file.",
    part: "Pages",
    disabled: false,
  },
  {
    id: "HIDE_TOOLTIP_DRILLTROUGH_PAGES",
    name: "Tooltip and Drillthrough pages should be hidden",
    description:
      "Reports a test fail if a page of type Tooltip or Drillthrough is visible. To disable this rule, mark it as disabled in the base rules file.",
    disabled: false,
  },
  {
    id: "ENSURE_THEME_COLOURS",
    name: "Ensure charts use theme colours",
    description:
      "Check that charts (excluding textboxes) avoid custom colours and use theme colours instead. To disable this rule, mark it as disabled in the base rules file.",
    part: "Pages",
    disabled: false,
  },
  {
    id: "ENSURE_PAGES_DO_NOT_SCROLL_VERTICALLY",
    name: "Ensure pages do not scroll vertically",
    description:
      "Returns an array of visible page names with a height great than 720px. Modify the rule parameter value if a different maximum height value is required. To disable this rule, mark it as disabled in the base rules file.",
    disabled: false,
  },
  {
    id: "ENSURE_ALTTEXT",
    name: "Ensure alternativeText has been defined for all visuals",
    description: "Alt-text is required for screen readers",
    part: "Pages",
    disabled: true,
  },
];
