#!/usr/bin/env node
// Usage: node scripts/sync-version.mjs
//
// Writes packages/core/src/version.ts from packages/core/package.json, so the core can report its
// version without reading a file at run time (it runs in the browser). The CLI takes its own
// version from its package.json at bundle time (packages/cli/build.mjs). It also writes the CLI's
// version into the skill the CLI ships (packages/cli/skill/SKILL.md), in its description and its
// metadata, so a stale installed copy shows. The version and skill tests fail when the generated
// file, the skill, or the two package versions are out of step.
import { readFileSync, writeFileSync } from "node:fs";

const { version } = JSON.parse(readFileSync("packages/core/package.json", "utf8"));
const out = "packages/core/src/version.ts";
writeFileSync(
  out,
  `// Generated by scripts/sync-version.mjs from packages/core/package.json. Do not edit by hand.\nexport const VERSION = ${JSON.stringify(version)};\n`,
);
console.log(`wrote ${version} to ${out}`);

const cli = JSON.parse(readFileSync("packages/cli/package.json", "utf8")).version;
const skill = "packages/cli/skill/SKILL.md";
writeFileSync(
  skill,
  readFileSync(skill, "utf8")
    .replace(/ pbiplint \d+\.\d+\.\d+[^\s.]*\.$/m, ` pbiplint ${cli}.`)
    .replace(/^ {2}version: "[^"]+"$/m, `  version: "${cli}"`),
);
console.log(`wrote ${cli} to ${skill}`);
