#!/usr/bin/env node
// Usage: node scripts/sync-version.mjs
//
// Writes packages/core/src/version.ts from packages/core/package.json, so the core can report its
// version without reading a file at run time (it runs in the browser), and pins the alias's
// dependency on the CLI to the same version. The CLI takes its own version from its package.json
// at bundle time (packages/cli/build.mjs). The version tests fail when the generated file, the
// three package versions, or the alias's pin are out of step.
//
// The pin needs writing because `npm version -w` bumps a workspace's own version and leaves a
// sibling workspace's dependency range alone, so a bump would otherwise leave the alias pointing
// at the version before it.
import { readFileSync, writeFileSync } from "node:fs";

const { version } = JSON.parse(readFileSync("packages/core/package.json", "utf8"));
const out = "packages/core/src/version.ts";
writeFileSync(
  out,
  `// Generated by scripts/sync-version.mjs from packages/core/package.json. Do not edit by hand.\nexport const VERSION = ${JSON.stringify(version)};\n`,
);
console.log(`wrote ${version} to ${out}`);

const manifest = "packages/alias/package.json";
const pkg = JSON.parse(readFileSync(manifest, "utf8"));
if (pkg.dependencies?.pbiplint !== version) {
  pkg.dependencies.pbiplint = version;
  writeFileSync(manifest, `${JSON.stringify(pkg, null, 2)}\n`);
  console.log(`pinned pbiplint ${version} in ${manifest}`);
}
