/// Disconnected security table — maps user emails to regions for dynamic RLS. Stays disconnected on purpose; a relationship to Customer would put security data in the field list and risks leaking it.
table 'User Region'
	lineageTag: 96220470-40d4-5c2b-b856-51de3028a086

	/// Authenticated user's UPN. Compared against USERPRINCIPALNAME() in the Regional Manager role's filter expression.
	column 'User Email'
		dataType: string
		lineageTag: e0415c7a-dd2f-555d-8de3-76eb1c80b063
		summarizeBy: none
		sourceColumn: User Email

		annotation SummarizationSetBy = Automatic

	/// Region the user is allowed to see. Multiple rows per user expand the user's accessible region set.
	column Region
		dataType: string
		lineageTag: 5a773f12-4ce3-5cb6-a43a-fb358ea33fdd
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'User Region' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Demo\Data\user_region.csv"), [Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"User Email", Text.Type}, {"Region", Text.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

