// Generated by scripts/sync-rule-pages.mjs from the first paragraph of each rule page's
// "What it checks" section. Do not edit by hand: edit the page under rules/ and rerun the script.

/** What each rule checks, one paragraph in pbiplint's own words, keyed by rule id. */
export const RULE_SUMMARIES: Readonly<Record<string, string>> = {
  ACTION_WITHOUT_DESTINATION:
    "Buttons, shapes, and images whose page navigation, drillthrough, or bookmark action is switched on but has no destination: the property that holds the destination for the action's type is missing from visual.json or empty.",
  ADD_DATA_CATEGORY_FOR_COLUMNS:
    "Columns with no data category whose name contains country, continent, or city and whose type is text, or whose name is exactly latitude or longitude and whose type is decimal or double.",
  "AVOID_BI-DIRECTIONAL_RELATIONSHIPS_AGAINST_HIGH-CARDINALITY_COLUMNS":
    "Columns in a bi-directional relationship that have more than 100,000 distinct values. Cardinality is a statistic of the loaded data, not of the model files, so pbiplint lists this rule but does not run it: it needs column statistics that only a live model carries.",
  AVOID_DUPLICATE_MEASURES:
    "Two or more measures whose DAX is identical once spaces, tabs, and line breaks are removed. Every copy is reported.",
  "AVOID_EXCESSIVE_BI-DIRECTIONAL_OR_MANY-TO-MANY_RELATIONSHIPS":
    "Models where bi-directional relationships plus many-to-many relationships make up more than 30 percent of all relationships. The finding is on the model, not on any one relationship.",
  AVOID_FLOATING_POINT_DATA_TYPES:
    "Columns of any kind whose data type is Double, which Power BI Desktop calls Decimal Number.",
  AVOID_INVALID_DESCRIPTION_CHARACTERS:
    "Descriptions containing a control character other than whitespace. Tabs and line breaks are allowed.",
  AVOID_INVALID_NAME_CHARACTERS:
    "Object names containing a control character that is not whitespace. The whitespace control characters are left out of the test; `SPECIAL_CHARS_IN_OBJECT_NAMES` reads names for a tab, a line feed, and a carriage return.",
  AVOID_SHOW_ITEMS_WITH_NO_DATA:
    "Visuals with Show items with no data turned on for any of their field wells.",
  AVOID_STRUCTURED_DATA_SOURCES_WITH_PROVIDER_PARTITIONS:
    "Partitions whose source is a legacy query, a provider partition, that points at a structured data source.",
  AVOID_THE_USERELATIONSHIP_FUNCTION_AND_RLS_AGAINST_THE_SAME_TABLE:
    "Tables that have a row-level security filter in any role and are named as the second argument of USERELATIONSHIP in a measure.",
  "AVOID_USING_'1-(X/Y)'_SYNTAX":
    "Expressions with a number, then plus or minus, then either `SUM('Table'[Column])` followed by a division operator, or a call to DIVIDE. The common shape is `1 - SUM(Sales[Cost]) / SUM(Sales[Amount])`.",
  "AVOID_USING_MANY-TO-MANY_RELATIONSHIPS_ON_TABLES_USED_FOR_DYNAMIC_ROW_LEVEL_SECURITY":
    "Regular tables that carry a row-level security filter in any role and take part in a many-to-many relationship.",
  AVOID_USING_THE_IFERROR_FUNCTION: "Measures and calculated columns that call IFERROR.",
  BROKEN_ACTION_TARGET:
    "Buttons, shapes, and images whose page navigation, drillthrough, or bookmark action names a page or a bookmark the report does not have, matched against the `name` in each page.json and bookmark file.",
  BROKEN_BOOKMARK_REFERENCE:
    "Bookmarks whose active page, or another page they capture, is not in the report, or which capture a visual that is not on its page, matched against the `name` in each page.json and visual.json.",
  BROKEN_FIELD_REFERENCE:
    "References in the report to a table, column, measure, hierarchy, or hierarchy level that the model does not have, wherever the report names a field: a visual's wells, formatting, and sort, a filter on a visual, a page, or the whole report, a drillthrough or tooltip page's fields, and a bookmark.",
  CALCULATION_GROUPS_WITH_NO_CALCULATION_ITEMS:
    "Calculation groups that contain no calculation items.",
  "CHECK_IF_BI-DIRECTIONAL_AND_MANY-TO-MANY_RELATIONSHIPS_ARE_VALID":
    "Every relationship that is bi-directional, many-to-many, or both. This is a review list at info severity, not a defect.",
  "CHECK_IF_DYNAMIC_ROW_LEVEL_SECURITY_(RLS)_IS_NECESSARY":
    "Row-level security filters that call USERNAME or USERPRINCIPALNAME. Reported per table permission, at info severity.",
  DATA_COLUMNS_MUST_HAVE_A_SOURCE_COLUMN:
    "Data columns with no source column. Calculated columns are not checked.",
  "DATE/CALENDAR_TABLES_SHOULD_BE_MARKED_AS_A_DATE_TABLE":
    "Tables with date or calendar in the name that are not marked as a date table, meaning the data category is not Time or no DateTime column is marked as the key.",
  DATECOLUMN_FORMATSTRING:
    "DateTime columns with date in the name whose format string is not exactly `mm/dd/yyyy`.",
  DAX_COLUMNS_FULLY_QUALIFIED:
    "Measures and row-level security filters that refer to a column by its bare name, `[Column]`, instead of `'Table'[Column]`.",
  DAX_MEASURES_UNQUALIFIED:
    "Measures, calculated columns, calculated tables, and calculation items that refer to a measure with a table prefix, `'Table'[Measure]`.",
  DEFAULT_PAGE_NAME:
    "Pages whose display name in page.json has the shape `Page <n>`, `Duplicate of <name>`, or `<name> (copy)`: the names English Power BI Desktop gives a new page and a duplicated one, and a name marked as a copy. The rule also matches the forms Desktop-saved files show for a new or duplicated page in other languages, such as `Seite <n>` and `Doublon de <name>`.",
  ENSURE_ALTTEXT:
    "Visuals other than shapes whose alt text is missing or empty. A visual group is checked by its own alt text, the one set on the group rather than on the visuals inside it.",
  ENSURE_PAGES_DO_NOT_SCROLL_VERTICALLY:
    "Visible pages taller than the threshold, 720 pixels by default.",
  ENSURE_TABLES_HAVE_RELATIONSHIPS:
    "Tables with no relationship to any other table. Calculation groups are not checked.",
  ENSURE_THEME_COLOURS:
    "Visuals other than text boxes with a colour property set to a hex value instead of a theme colour, including a hex value inside a conditional formatting rule or a gradient.",
  EVALUATEANDLOG_SHOULD_NOT_BE_USED_IN_PRODUCTION_MODELS: "Measures that call EVALUATEANDLOG.",
  EXPRESSION_RELIANT_OBJECTS_MUST_HAVE_AN_EXPRESSION:
    "Measures, calculated columns, and calculation items whose expression is empty.",
  FILTER_COLUMN_VALUES:
    "CALCULATE or CALCULATETABLE whose first filter argument is `FILTER('Table', 'Table'[Column] ...)`.",
  FILTER_MEASURE_VALUES_BY_COLUMNS:
    "CALCULATE or CALCULATETABLE whose first filter argument is `FILTER('Table', [Measure] ...)`.",
  FILTERS_PANE_STATE:
    "A report whose Filters pane, as saved in report.json, is not in the state the project's policy expects, open or closed. Without a policy the rule reports nothing.",
  FIRST_LETTER_OF_OBJECTS_MUST_BE_CAPITALIZED:
    "Tables, measures, hierarchies, calculated columns, calculated tables, and calculation groups whose first character has an upper case form and is not upper case.",
  FIX_REFERENTIAL_INTEGRITY_VIOLATIONS:
    "Relationships where the many side holds key values that do not exist on the one side. The count of offending rows is a statistic of the loaded data, not of the model files, so pbiplint lists this rule but does not run it: it needs statistics that only a live model carries.",
  "FORMAT_FLAG_COLUMNS_AS_YES/NO_VALUE_STRINGS":
    "Visible columns whose name starts with Is and whose type is whole number, and visible columns whose name ends with the word Flag after a space and whose type is not text.",
  HIDDEN_VISUAL_WITH_FIELDS:
    "Visuals hidden in the Selection pane, with their own eye icon or with that of a group they sit in, that still have fields in their wells.",
  HIDE_FACT_TABLE_COLUMNS:
    "Visible numeric columns that a measure aggregates directly with a fully qualified reference, such as `SUM('Sales'[Amount])`. COUNT, COUNTBLANK, SUM, AVERAGE, MIN, MAX, DISTINCTCOUNT, VALUES, DISTINCT, and the A-suffixed COUNTA, AVERAGEA, MAXA, and MINA count as aggregations.",
  HIDE_FOREIGN_KEYS:
    "Visible columns whose name matches the from column of a relationship whose from side is many. Only the from cardinality is tested, so a many-to-many relationship counts here too, not just many-to-one.",
  HIDE_TOOLTIP_DRILLTROUGH_PAGES: "Tooltip pages and drillthrough pages that are not hidden.",
  INACTIVE_RELATIONSHIPS_THAT_ARE_NEVER_ACTIVATED:
    "Inactive relationships that no measure or calculation item activates with USERELATIONSHIP.",
  INTEGER_FORMATTING:
    "Measures whose static format string is not a recognized whole-number, currency, or percentage format. The only format strings the rule accepts are `#,0`, `#,0.0`, and any string containing `$` or `%`. A measure with no format string at all fires too, and that is the common case: the rule reads only the format string, so it cannot tell an unformatted currency or ratio from an unformatted count.",
  ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS:
    "Hidden columns, or columns in hidden tables, that still have IsAvailableInMdx set to true and are not used to sort another column, in a hierarchy, or in a variation, and do not themselves sort by another column.",
  LANDING_PAGE_NOT_SET:
    "A report whose pages.json sets no landing page, so it opens on the page that was active when it was last saved, or, when pages.json records no active page either, on the first page.",
  LARGE_TABLES_SHOULD_BE_PARTITIONED:
    "Tables with more than 25 million rows and a single partition. The row count is a statistic of the loaded data, not of the model files, so pbiplint lists this rule but does not run it: it needs statistics that only a live model carries.",
  "LIMIT_ROW_LEVEL_SECURITY_(RLS)_LOGIC":
    "Tables whose row-level security filter, in any role, calls RIGHT, LEFT, UPPER, LOWER, or FIND.",
  "MANY-TO-MANY_RELATIONSHIPS_SHOULD_BE_SINGLE-DIRECTION":
    "Many-to-many relationships with bi-directional cross filtering.",
  MARK_PRIMARY_KEYS:
    "Columns on the one side of a relationship, outside date tables, that are not marked as the table's key.",
  MEASURES_SHOULD_NOT_BE_DIRECT_REFERENCES_OF_OTHER_MEASURES:
    "Measures whose whole expression is a reference to another measure, such as `[Total Sales]`.",
  MEASURES_USING_TIME_INTELLIGENCE_AND_MODEL_IS_USING_DIRECT_QUERY:
    "Measures and calculation items that call a time intelligence function, in a model where at least one table is in DirectQuery mode.",
  MINIMIZE_POWER_QUERY_TRANSFORMATIONS:
    "Power Query partitions whose M text contains Table.Combine, Table.Join, Table.NestedJoin, Table.AddColumn, Table.Group, Table.Sort, Table.Pivot, Table.Unpivot, Table.UnpivotOtherColumns, Table.Distinct, a native SQL query, or an OLE DB or ODBC query.",
  MODEL_SHOULD_HAVE_A_DATE_TABLE:
    "Models with no table that has the data category Time and a DateTime column marked as the key, which is what Mark as date table sets.",
  MODEL_USING_DIRECT_QUERY_AND_NO_AGGREGATIONS:
    "Models that have at least one DirectQuery table, no aggregation table (no column has an alternateOf mapping), and the PowerBI_V3 data source version, which is every project Desktop writes today.",
  "MONTH_(AS_A_STRING)_MUST_BE_SORTED":
    "Text columns with month in the name, but not months, that have no sort-by column.",
  MONTHCOLUMN_FORMATSTRING:
    "DateTime columns with month in the name whose format string is not exactly `MMMM yyyy`.",
  NOT_REACHED_FROM_REPORT:
    "Columns and measures that nothing in the report reaches, directly or through the model. The walk starts from every field the report names, both columns of every relationship except one to an auto date/time table, the columns that row-level and object-level security name, the default column of every variation, the columns of an aggregation table (the ones with an `alternateOf` mapping), and the fields the report's own measures reference, and it follows DAX references, sort-by and group-by columns, the detail column or table each mapping names, and calculated tables until nothing new is reached.",
  NUMERIC_COLUMN_SUMMARIZE_BY:
    "Visible whole number, decimal, or double columns whose default summarization is anything other than None.",
  OBJECTS_SHOULD_NOT_START_OR_END_WITH_A_SPACE:
    "Names that start or end with a space, for the model, tables, measures, hierarchies, perspectives, partitions, data columns, and calculated columns.",
  OBJECTS_WITH_NO_DESCRIPTION:
    "Visible tables, columns, measures, and calculation groups with no description. Visibility is the object's own flag.",
  OPENING_PAGE_INVALID:
    "A pages.json whose landing page names a page the report does not have, or, when no landing page is set, whose active page names a page the report does not have or a page hidden from readers.",
  PARSE_ISSUE:
    "Lines the TMDL parser could not use: space indentation, an unterminated code fence, a line at an impossible indentation, a line in no form the parser recognizes, a line at the root of a file that TMDL does not allow there (a misspelt `table`, a `column` or a property that lost its tabs, or an annotation with lines under it, for example), and a `///` description with a blank line between it and its declaration; a report JSON file that is not valid JSON or carries a merge conflict marker; and a report file Microsoft publishes a schema for, such as report.json or a page.json, whose content is not a JSON object.",
  PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES:
    "Regular tables with exactly one partition whose name differs from the table name. Calculated tables and calculation groups are not checked.",
  PERCENTAGE_FORMATTING:
    "Measures with a percent format string other than `#,0.0%;-#,0.0%;#,0.0%`.",
  PERSPECTIVES_WITH_NO_OBJECTS:
    "Perspectives that contain no tables. The rule reads only a perspective's table entries, which is enough: each column, measure, and hierarchy a perspective includes sits under the entry for its table, so with no table entry it includes nothing.",
  PROVIDE_FORMAT_STRING_FOR_MEASURES:
    "Visible measures with no format string and no dynamic format string.",
  REDUCE_ADVANCED_FILTERS:
    "Pages with more visuals carrying an Advanced filter with a condition applied than the threshold, 4 by default.",
  REDUCE_NUMBER_OF_CALCULATED_COLUMNS:
    "Models with more than five calculated columns across all tables. Columns of calculated tables do not count, and the finding is on the model.",
  REDUCE_OBJECTS_WITHIN_VISUALS:
    "Visuals with more entries in their field wells than the threshold, 6 by default, counting each column, measure, visual calculation, or sparkline in any of the visual's wells as one.",
  REDUCE_PAGES: "Reports with more pages than the threshold, 10 by default, hidden pages included.",
  REDUCE_TOPN_FILTERS:
    "Pages with more visuals carrying a Top N filter than the threshold, 4 by default.",
  REDUCE_USAGE_OF_CALCULATED_COLUMNS_THAT_USE_THE_RELATED_FUNCTION:
    "Calculated columns whose DAX calls RELATED.",
  REDUCE_USAGE_OF_CALCULATED_TABLES: "Every calculated table. Calculation groups are not included.",
  "REDUCE_USAGE_OF_LONG-LENGTH_COLUMNS_WITH_HIGH_CARDINALITY":
    "Text columns where more than 500,000 rows hold values longer than 100 characters. That count is a statistic of the loaded data, not of the model files, so pbiplint lists this rule but does not run it: it needs statistics that only a live model carries.",
  REDUCE_VISUALS_ON_PAGE:
    "Pages with more visuals than the threshold, 20 by default, counting every visual except shapes, slicers, buttons, text boxes, and a visual hidden by `isHidden` in its own visual.json.",
  RELATIONSHIP_COLUMNS_SAME_DATA_TYPE: "Relationships whose two columns have different data types.",
  RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE:
    "Any column that takes part in a relationship and is not a whole number.",
  "REMOVE_AUTO-DATE_TABLE":
    "Calculated tables generated by the Auto date/time option, whose names start with DateTableTemplate_ or LocalDateTable_.",
  REMOVE_DATA_SOURCES_NOT_REFERENCED_BY_ANY_PARTITIONS:
    "Data sources that no partition names and that appear nowhere in any partition's query or M text.",
  REMOVE_REDUNDANT_COLUMNS_IN_RELATED_TABLES:
    "Columns that take part in no relationship and share a name with a column on a table at the to side of a relationship from their own table.",
  REMOVE_ROLES_WITH_NO_MEMBERS: "Roles with no members.",
  REMOVE_UNUSED_CUSTOM_VISUALS:
    "Custom visuals from AppSource that the report registers in report.json and that no visual on any page uses.",
  REPORT_LEVEL_MEASURES:
    "Measures defined in the report's reportExtensions.json rather than in the model, reported when the model the report reads is in the input, so that each can move into it.",
  SET_ISAVAILABLEINMDX_TO_TRUE_ON_NECESSARY_COLUMNS:
    "Columns with IsAvailableInMdx set to false that are used to sort another column, appear in a hierarchy or a variation, or sort by another column.",
  SLICER_SELECTION_SAVED:
    "Slicers saved with a selection, so that the report opens with it applied: any visual whose visual.json holds a `filter` with a condition under `objects.general`, which is where Power BI Desktop saves the selection of a slicer, button slicer, list slicer, input slicer, or `filterSlicer`, and of a custom slicer from AppSource that filters through the Visual Filters API. It is info without a policy, and a warning when the project's policy expects no saved selections.",
  SNOWFLAKE_SCHEMA_ARCHITECTURE:
    "Tables that are on the from side of one relationship and the to side of another, which is what a dimension related to a sub-dimension looks like.",
  SPECIAL_CHARS_IN_OBJECT_NAMES: "Names containing a tab, line feed, or carriage return.",
  SPLIT_DATE_AND_TIME:
    "DateTime columns holding values that are not at midnight. Whether any row carries a time is a statistic of the loaded data, not of the model files, so pbiplint lists this rule but does not run it: it needs statistics that only a live model carries.",
  TAB_ORDER_FOLLOWS_LAYOUT:
    "Pages whose tab order, the order keyboard users move through the visuals in, disagrees with the order the layout reads in: rows from top to bottom, and left to right within a row. The rule checks this only when the project's policy asks for tab order to follow the layout, and reports nothing without it.",
  TRIM_OBJECT_NAMES:
    "Names that start or end with a space, across every named object type in the model.",
  UNNECESSARY_COLUMNS:
    "Hidden columns, or columns in hidden tables, that nothing references: no DAX expression, relationship, hierarchy, sort-by column, row-level security filter, or object-level security rule.",
  UNNECESSARY_MEASURES:
    "Hidden measures, or measures on hidden tables, that no DAX expression references.",
  "UNPIVOT_PIVOTED_(MONTH)_DATA":
    "Tables that have a numeric column for each of Jan, Feb, Mar, Apr, May, and Jun, matched as substrings of the column names.",
  USE_THE_DIVIDE_FUNCTION_FOR_DIVISION:
    "Expressions that use the division operator right after a closing bracket or parenthesis, such as `[Sales] / [Cost]` or `SUM(...) / SUM(...)`. A slash that starts a comment is ignored.",
  USE_THE_TREATAS_FUNCTION_INSTEAD_OF_INTERSECT:
    "Measures and calculation items that call INTERSECT.",
  VISUAL_OUTSIDE_PAGE:
    "Visuals whose box runs past the right or bottom edge of their page by a pixel or more: `x` plus `width` beyond the page's width, or `y` plus `height` beyond its height.",
  VISUAL_WITHOUT_FIELDS:
    "Data visuals with no field in any of their wells. Every visual type counts as a data visual, custom visuals included, except visual groups and the types that need no fields by design, such as shapes, text boxes, images, and buttons.",
};
