table Store
	lineageTag: 376faf0a-df28-4e4b-809e-c03a48d54a2c

	/// Number of distinct stores.
	measure 'Store Count' = DISTINCTCOUNT(Store[Store ID])
		formatString: #,##0
		lineageTag: f1bd6643-6725-4e7b-8607-da10339218a0

	column 'Store ID'
		dataType: int64
		isHidden
		lineageTag: 0988d391-c845-4cdd-87e8-8ab8cbf9e9c1
		summarizeBy: none
		sourceColumn: Store ID

	column 'Store Name'
		dataType: string
		lineageTag: 5d77d8ef-bce6-48eb-80fd-e3ec7245fe75
		summarizeBy: none
		sourceColumn: Store Name

	column 'Store Type'
		dataType: string
		lineageTag: ed73b4fe-f024-46fe-9eb4-e40a7023b776
		summarizeBy: none
		sourceColumn: Store Type

	column City
		dataType: string
		lineageTag: 54a8d601-d38c-4e5b-920b-592be2d1f029
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

	column State
		dataType: string
		lineageTag: 5ab57d89-6fe1-4a90-86ab-b3d9575c5e6d
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

	column Region
		dataType: string
		lineageTag: 2a731a48-a81c-4647-82f3-3ef4488def17
		summarizeBy: none
		sourceColumn: Region

	column Country
		dataType: string
		lineageTag: 0b485e26-3468-4df3-b97a-bc016fd749d0
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

	column 'Open Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: cd9a2eab-f430-4555-8b5e-373812488786
		summarizeBy: none
		sourceColumn: Open Date

		variation Variation
			isDefault
			relationship: fec0f1bb-2929-410d-9485-8332687e4569
			defaultHierarchy: LocalDateTable_ef30d063-6216-4d63-895c-419361657bc0.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	/// Source latitude is randomized and does not match the city — hidden to keep it off maps.
	column Latitude
		dataType: double
		isHidden
		lineageTag: a5074aa0-48c7-4bab-9203-5ed76bc5c0db
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

	/// Source longitude is randomized and does not match the city — hidden to keep it off maps.
	column Longitude
		dataType: double
		isHidden
		lineageTag: 9953c892-b656-4324-8560-2e68f5f15aa9
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

	column 'Square Feet'
		dataType: int64
		formatString: #,##0
		lineageTag: b02f66a2-7d3b-4d37-af98-e301f81037e8
		summarizeBy: sum
		sourceColumn: Square Feet

		annotation SummarizationSetBy = Automatic

	partition Store = m
		mode: import
		source =
				let
				    // Read the Store dimension CSV from the local Data folder
				    Source = Csv.Document(File.Contents("C:\Demo\Data\Store.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Typed Columns" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Store ID", Int64.Type}, {"Store Name", type text}, {"Store Type", type text}, {"City", type text},
				        {"State", type text}, {"Region", type text}, {"Country", type text}, {"Open Date", type date},
				        {"Latitude", type number}, {"Longitude", type number}, {"Square Feet", Int64.Type}})
				in
				    #"Typed Columns"

